-d C:\Users\24096\Desktop\example_basis\ex1\impl\gwsynthesis\fpga_project_scan.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\24096\Desktop\example_basis\ex1\src\fpga_project_scan.cst
-cfg C:\Users\24096\Desktop\example_basis\ex1\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
