-d E:\haoxy\doc\fpga\yitices_pro\fpga\ex1\impl\gwsynthesis\fpga_project_scan.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst E:\haoxy\doc\fpga\yitices_pro\fpga\ex1\src\fpga_project_scan.cst
-cfg E:\haoxy\doc\fpga\yitices_pro\fpga\ex1\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
