-d E:\haoxy\doc\fpga\yitices_pro\fpga\ex10\ee11\fpga_project_3\impl\gwsynthesis\fpga_project_3.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst E:\haoxy\doc\fpga\yitices_pro\fpga\ex10\ee11\fpga_project_3\src\pcs1.cst
-cfg E:\haoxy\doc\fpga\yitices_pro\fpga\ex10\ee11\fpga_project_3\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
