# 彩虹说话机配置文件
# 这个文件可以用于自定义应用的各种设置

# 界面设置
[UI]
window_title = "彩虹说话机"
window_width = 450
window_height = 320
window_resizable = false

# 颜色设置
[Colors]
colors = [
    "#FF6F61",  # 珊瑚红
    "#FFB347",  # 桃色
    "#FFF275",  # 淡黄
    "#8DE969",  # 浅绿
    "#4FC3F7",  # 天蓝
    "#9575CD",  # 紫色
    "#F06292"   # 粉色
]
color_change_interval = 200  # 毫秒

# 字体设置
[Fonts]
main_font_family = "微软雅黑"
main_font_size = 20
main_font_style = "bold"
button_font_family = "微软雅黑"
button_font_size = 14

# 语音设置
[Speech]
rate = 200          # 语音速度
volume = 0.8        # 音量 (0.0-1.0)
name_broadcast_interval = 1500  # 名字播报间隔（毫秒）

# 文本内容
[Texts]
funny_texts = [
    "你写的代码真是一团糟！",
    "又出bug了吧,气死我了！",
    "你这家伙能不能认真点？",
    "写代码别瞎搞行不行！",
    "这都能写错，服了你了！",
    "别再摸鱼了，赶紧干活！",
    "你是不是又忘了保存？",
    "代码乱七八糟，重写！",
    "你写的什么鬼东西！",
    "别再犯傻了，动动脑子！",
    "写代码能不能走点心？",
    "又报错了，气不气？",
    "你这水平还敢写代码？",
    "别再拖延了，快点写！",
    "写成这样不如不写！",
    "你是不是在逗我？",
    "代码写得跟屎一样！",
    "别再出错了，求你了！",
    "你能不能靠谱点？",
    "写代码别睡着了！",
    "你写的代码像没睡醒一样！",
    "这点小事都能写错，服气！",
    "你写的代码让我怀疑人生！",
    "你是不是把键盘当鼓敲？",
    "写成这样老板都要哭了！"
]

names = [
    "席睿康",
    "程天睿", 
    "王天一",
    "高祺享"
]

# 日志设置
[Logging]
level = "INFO"
format = "%(asctime)s - %(levelname)s - %(message)s"
file_path = "rainbow_speaker.log"
